### ISSUE TITLE
accessible spectrum-css properties?

### ISSUE THREAD

**Issue by dkipp** [adobe/coral-spectrum#1]
is it somehow possible to access the spectrum-css properties in my designs when using coral-spectrum?

// my themeable additions:
`#myOwnThing {
background-color: var(--spectrum-alias-background-color-default);
}`

**Comment by icaraps** [comment]
@dkipp they're not included by default. If you wish to use them, you can grab them from https://raw.githubusercontent.com/adobe/coral-spectrum/master/coral-theme-spectrum/src/styles/vars.css or one of the files from https://unpkg.com/@adobe/spectrum-css@2.13.0/dist/vars/
