### ISSUE TITLE
Coral-card overflow check unnecessary when no alerts are present

### ISSUE THREAD

**Issue by sharanyavinod** [adobe/coral-spectrum#28]
### Expected Behavior
Conditional checks for adding `${Class_name}--overflow` class to coral-card is done irrespective of whether alerts/banners are present for the card or not.

### Actual Behavior
Checks need to be done only when the card has at least one alert/banner.

#### Steps to Reproduce
Discovered while working on the conversion of `coral-icon` to `button is="coral-button"` in [1] for cloud-ready instances

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
Chrome Version 80.0.3987.87

#### Screenshots (if applicable)

[1]: https://jira.corp.adobe.com/browse/CQ-4274556

**Comment by habansal** [comment]
@sharanyavinod Since this is a public project (github - adobe), I don't think we should reference internal issues here.
So, I suggest that you update the `Steps to reproduce` to remove reference to CQ Jira issue and make it self-explanatory (maybe, in brief).
