### ISSUE TITLE
Coral Spectrum Tab uses only the color red to indicate that it's invalid

### ISSUE THREAD

**Issue by adobre90** [adobe/coral-spectrum#48]
### Expected Behavior

The Coral Spectrum Tab component shouldn't use only the color red to show that it is invalid, but also have a more obvious element. This would be an accessibility improvement, especially for color blind users.

### Actual Behavior

Coral Spectrum Tab only uses the color red to indicate that it's invalid.

### Reproduce Scenario (including but not limited to)

When working with a Coral Spectrum Tablist component and you have a Tab component set to invalid, the only difference is the red color.

#### Steps to Reproduce

1. Add Chromelens plugin for Google Chrome (https://chrome.google.com/webstore/detail/chromelens/idikgljglpfilbhaboonnpnnincjhjkd).
2. Start up the Coral Spectrum Tablist component examples page ( coral-component-tablist/examples/index.html ) by using `gulp`.
3. Go to http://127.0.0.1:9001/examples/. 
4. From Developer Tools, go to Chromelens and select one of the following: Achromatopsia (RGB-Blind), Protanopia ( Red - blind ).
5. Check that the invalid tab is resembling all the other tabs.

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
Google Chrome Version 80.0.3987.149 (Official Build) (64-bit)

#### Coral Spectrum version
4.3.1

#### Sample Code that illustrates the problem (use the Playground if possible)
Check coral-component-tablist/examples/index.html.

#### Screenshots (if applicable)
Example with Chromelens Achromatopsia:

![image](https://user-images.githubusercontent.com/53042848/78039972-75a0db00-7377-11ea-9680-ea5a31d7a8c2.png)

**Comment by icaraps** [comment]
Fixed with https://github.com/adobe/coral-spectrum/commit/282b4018145f78429ca5646936866e324f85694b
